---
title: "CorrigeDataCamp"
author: "Sofia Rivera Vidal"
date: "2026-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(writexl)
library(tidyverse)
library(readxl)
library(dplyr)
library(pdftools)
```

```{r}
nom_carpetas <- list.files(path='data', pattern = '.*_assignsubmission_file', full.names = TRUE)
#n_carpetas es un vector con la dirección de todos los elementos que hay dentro de la carpeta data.

df_apellidos <- c()
df_puntos <- c()
df_nombrepuntos <- c()
df_puntostexto <- c()
puntos_general <- c()
certificate_general <- c()

for (i in 1:length(nom_carpetas)){
  certificate_pdf <- FALSE
  puntos_txt <- FALSE #Se asume que no no están ninguno de los dos documentos.
  puntos <- NA
  nombre_puntos <- NA
  puntos_texto <- NA

  carpeta_direc <- list.files(path = nom_carpetas[i], full.names = TRUE)
  carpeta <- strsplit(carpeta_direc, '/')
  apellidos <- strsplit(carpeta[[1]][[2]], ',')[[1]][[1]]
  
  for (j in 1:length(carpeta_direc)){
    direc <- file.path(dirname(carpeta_direc[j]), "cert")
     if (grepl(direc, carpeta_direc[j])){
      certificate_pdf <- TRUE
    } else {
      puntos_txt <- TRUE
      puntos_direc <- carpeta_direc[j]
      nombre_puntos <- strsplit(puntos_direc, '/')[[1]][[3]]
      if (grepl('.pdf$', carpeta_direc[j])){
        archivo_puntos <- pdf_text(puntos_direc)
        puntos_texto <- paste(archivo_puntos, collapse = "\n")
      } else {
        archivo_puntos <- read_csv(puntos_direc, col_names = FALSE)
        puntos_texto <- trimws(readLines(puntos_direc))
      }
      puntos <- str_extract(string = archivo_puntos, pattern ='[0-9]{2,}')
    }
  }
  df_apellidos <- c(df_apellidos, apellidos)
  df_puntos <- c(df_puntos, puntos)
  df_puntostexto <- c(df_puntostexto, puntos_texto)
  df_nombrepuntos <- c(df_nombrepuntos, nombre_puntos)
  puntos_general <- c(puntos_general, puntos_txt)
  certificate_general <- c(certificate_general, certificate_pdf)
}

df_apellidos <- as.character(unlist(df_apellidos))
df_puntos <- as.integer(unlist(df_puntos))
df_nombrepuntos <- as.character(unlist(df_nombrepuntos))
df_puntostexto <- as.character(df_puntostexto)

df <- as.data.frame(cbind(df_apellidos, df_puntos, df_nombrepuntos, df_puntostexto))
colnames(df) <- c("apellidos", "puntos", "NomFile", "Puntos")
rownames(df) <- NULL
df <- df %>% arrange(apellidos)

write_xlsx(df, "data/NotasRIntermedio.xlsx")

variables <- str_extract_all(string=df$NomFile, pattern = '.+')|>unlist() |> table() |> as.data.frame() |> dplyr::arrange(desc(Freq))
variables #Diferentes nombres que toma el archivo de puntos con su frecuencia
length(variables) #Cantidad de nombres diferetes que toma el archivo de puntos

#Se comprueba si hay algún elemento que no esté. Si da TRUE, habrá algún alumno que no lo habrá entregado, si da FALSE, quiere decir que todoslo han entregado. Esto es, en cualquier caso, sobre los alumnos que han realizado entregas (no de todos los alumnos matriculados en la asignatura ya que en este punto todavía no se ha hecho uso del archivo con dicha información).
sum(puntos_general==FALSE)>0
sum(certificate_general==FALSE)>0
```

```{r}
alumnos <- read_xlsx("data/AlumnosTD25_26.xlsx")

colnames(df)[1] <- 'Apellido(s)' #Se le pone el mismo nombre a la columna de los apellidos que en el nuevo archivo para poder unirlos mediante esta, ya que es la única columna que tienen en común.

alumnos_notas <- full_join(alumnos, df)
write_xlsx(alumnos_notas, "data/AlumnosNotas.xlsx")
```

```{r}
alumnos <- read_xlsx("data/AlumnosTD25_26.xlsx")

colnames(df)[1] <- 'Apellido(s)' #Se le pone el mismo nombre a la columna de los apellidos que en el nuevo archivo para poder unirlos mediante esta, ya que es la única columna que tienen en común.

alumnos_notas <- left_join(alumnos, df)
write_xlsx(alumnos_notas, "data/AlumnosNotas.xlsx")
```